ASPECTS = {
  editing: {
    'editing' => 100,
    'the edit' => 100,
    'effects' => 70,
    'post production' => 50,
  },

  sound: {
    'sound' => 100,
    'music' => 100,
    'dolby' => 100,
    'audio' => 100,
    'sounds' => 100,
    'soundtrack' => 100,
    'surround' => 80,
    'ears' => 20,
    'score' => 10,
  },

  plot: {
    'story' => 100,
    'storyline' => 100,
    'plot' => 100,
    'villain' => 100,
    'protagonist' => 100,
    'spoiler' => 100,
    'narrative' => 80,
    'narration' => 80,
    'narratively' => 80,
    'twists' => 70,
    'the part' => 70,
    'told through' => 70,
    'pacing' => 60,
    'rhythm' => 60,
    'conflict' => 60,
    'scenario' => 50,
    'explanation' => 50,
    'structurally' => 50,
    'nostalgia' => 50,
    'structured' => 50,
    'revolves' => 50,
    'paced' => 50,
    'about a' => 40,
    'guessed it' => 30,
    'tale' => 30,
    'characters' => 50,
    'character' => 50,
    'journey' => 30,
    'persona' => 20,
  },

  dialog: {
    'dialog' => 100,
    'dialogue' => 100,
    'script' => 100,
    'speech' => 100,
    'spoken' => 90,
    'jokes' => 90,
    'funny' => 90,
    'talk' => 90,
    'talks' => 90,
    'comedy' => 80,
    'discussion' => 80,
    'conversation' => 80,
    'language' => 70,
    'delivery' => 50,
    'written' => 50,
  },

  cast: {
    'acting' => 100,
    'overacting' => 100,
    'actors' => 100,
    'actresses' => 100,
    'director' => 100,
    'cast' => 100,
    'overacted' => 100,
    'performance' => 90,
    'performances' => 90,
    'portrayal' => 90,
    'depiction' => 90,
    'characterization' => 90,
    'impersonation' => 90,
    'act' => 70,
    'star' => 70,
    'played' => 70,
    'plays a' => 70,
    'role' => 70,
    'persona' => 50,
  },

  vision: {
    'visuals' => 100,
    'visually' => 100,
    'computer effects' => 100,
    'computer graphics' => 100,
    'imax' => 100,
    'cgi' => 100,
    '3d' => 100,
    'graphics' => 100,
    'visual' => 100,
    'special effects' => 100,
    'graphic' => 90,
    'colour' => 90,
    'color' => 90,
    'lighting' => 90,
    'blurry' => 80,
    'graphic' => 80,
    'gore' =>80,
    'lifelike' => 80,
    'cool to look at' => 50,
    'spectacle' => 60,
    'the view' => 40,
    'lens' => 10,
    'designs' => 8,
  },

  length: {
    'dragged' => 100,
    'flew by' => 80,
    'hours' => 70,
    'drawn out' => 70,
    'slow' => 70,
    'bloated' => 70,
    'superfluous' => 70,
    'boring' => 50,
  },

  credibility: {
    'credibility' => 100,
    'true to the book' => 100,
    'believable' => 100,
    'improbable' => 100,
    'far-fetched' => 100,
    'implausible' => 100,
    'capturing' => 100,
    'true' => 80,
    'truthful' => 80,
    'truthfully' => 70,
    'facts' => 70,
    'missing details' => 60,
    'didn\'t buy' => 50,
  },

  cinematography: {
    'cinematography' => 100,
    'film making' => 100,
    'filmmaking' => 100,
    'direction' => 80,
    'director' => 80,
    'production' => 80,
    'shooting' => 80,
    'camera movement' => 80,
    'scene' => 80,
    'scenes' => 80,
    'camera' => 30,
    'image' => 20,
  },

  concept: {
    'concept' => 100,
    'interesting idea' => 100,
    'notion' => 100,
    'idea works' => 50,
  },

  novelty: {
    'novel idea' => 100,
    'original' => 100,
    'something different' => 100,
    'freshness' => 100,
    'charming' => 100,
    'quirky' => 100,
    'something new' => 100,
    'fresh' => 100,
    'inventive' => 100,
    'revolutionary' => 100,
    'unique' => 100,
    'unlike any other' => 100,
    'ground breaking' => 100,
    'subtler gems' => 70,
    'the pap' => 70,
    'like that\'s new' => 70,
    'stand out' => 50,
  }
}
