source 'https://rubygems.org'

gem 'rails', '4.1.8'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'slim'

gem 'googleajax'

group :development do
  gem 'sqlite3'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'vcr'
  gem 'webmock'
  gem 'capybara'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
